workflows:
  react-native:
    name: postwallet-ios
    max_build_duration: 60

    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(Z0FBQUFBQmdzeHkycDN5Sll1blBrcGZVM2FJSE42RnZpR21HUXkxY1JHMUljM2lsQUs2UFRDWWlpeEp5UnpQRmpFS3BPOU9WY1ZLckNZSVlNNUVrYU5SalRDZWZFUkJMbzFFeGVfeVB0ZFl5M1Y4eDZfTzBENDVXRm1UYkh5X29NVjdCaS1aV21UZWE=)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(Z0FBQUFBQmdzeHluTHJndUx6VS0wN00zUXphQ3YtbzFaX2k5cmZGN0NYVTNheWxxMy1hdk9fZmxoXy01T3Y1Mkt3Yi15MmtmRFJOQWxjR3JpNVBNODdRMjBvekF1ZG9tYWc9PQ==)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmdzeUZtYVp1bXRqUHVJRTNYZnFncGNzaUppX21lVnUxeGdhRU9KT09abURIcDh4MExlaExicjNyNGpHX3VjTWp4R1RNcFNodVpkSGVrMmZkMGJjVGVMbFItMi1GVFl2akZYdHBnRFE4SlBHMHJvQ01oNU9xck1vcTJ6M19lUlFjcDVDSHQ2MVNnMWh0ZFZEck0zWjh5Y0Zwa21LTjNpR3lLVmtQM3FKdVZVLXVXZ0xlTzVHS3FsTWJSNUt4QXlicFE0U3J2dHR4NEloRDk0ek9sd25XVi1ZUzdyVGhkTGV6cHJpUEU1Y1pzWndYODREcWRvaVZZVjFLdUgxMFRWN2lhbUFZM3hhdG1OREN1RTlnZi1tRHE2WHAzNlNiVk9xazE0RWpHakdvaUJ3aTZxTW1jUWJKR3hQUnB4TGdMWjA4YmltWk16YVhTR1pHRnhpQWdqdEEtNVQ4ZU9NZU1uZWxEOGNVTWdFWHIwX1h6emdYWXM0MWtFUFVoUEtVQXA1LUhpS0xyXzJCN25VZURXT3pjWC1sVGxMVTZOeFcteTIzaFprNDFtdnFJWV9mTXFVWT0=)
        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmdzeF9CVmczZVpwMmVIdk5BV1FPSkhTTzNJa3VnN0VJc1lYZk5yT1NmSTFhcXlWZE1IYXpMcUlZOTg5VEs0S1RBVDRUZm9IcExfMXI1VWt1RDJVNnhfZFk1dlVmUFpJZWpHbUpkRzd3RG9XNjd6dnF1bDN5UUF0YlZZa3lnRms2N0pPOEt2ZWg1YjNEd09KWDktM0Z3SWxVMkRYdnF6dzltOEVIb0pCYW1mTVBtMmpmZDBndDBjc2Q0Sk1sUGFTT2o4VXdFNUVXckkzT19GeDhQc0s4a3hfY1VNa01CaWI1bmlDOFV1MjZLeGhlaGVla2JlYWNsbXVMWHNLQ3NRRF82OWZxTW9ZN1NGWHBKZEpYeEVIdEFrSTZKVDdkQ1ZGZmJEY3lPdDJoMlRWUXBzcWJMeUc0Z3U4Sk9yVVBLbm9DTkNBTkxXNC10Z256eFpDalBmY0VIQUx2OXRaMWVNZ1QzQTc1UmNEYzBzblZpMDZwUmFwRTZwZUZNcURlNmZmb19wcjFDaFZocXpMY0lyU0NOSmhpeE8zS0ZOZjlVUEowaEgyODVjT1FXaEdHR044R01PMmhQRW0ta21lby1GZlgyNmlDNWt0Y2FJWmpCLTRwbWkybm5PQnBHTHZiZnVCcW43UDFRS2p1bTlDN09DZmpNaUxNUF81U1Y2NUo5WUc1UEZNbmpVTmZ4NF94dnV3R0c3OGltTWdiYVdINXdNRm91Rl9tc3d4T2J1UzBfbHRKUXY1UkhKTmFvSTNELUFhcmNaLWx0UkY2c0ZTeThyUzNndVJaZFJVR21MWEJKX2JNT2tSdml3a0ZvZWRjZ3dpekc1UlpxajExb2o2VVk1S096UFJ6OGVyYUZjanloZWxCLTlKU1ROc0VEeElEWDVTaUR2Yl9SUGhLZ21QZEtqMFRISGNxTnJjYkVFd3B5LVkyLWlmNG9VeEdieVBnSnBLVDVRaW0yOEYwVzlXOTI0ZVg3SnNYOEhnTzFLcGQtUXJaakZRMTc1dXgxX1BPdU5OUUNtZFBwRGl4R0VObEJaSUFZSF9IUndXX2xzbE96ZEx6T2ttMkdxOVcwV0Etc2tYYXF5NFhWa3J0WEFhTlFySlFrY2Y1dlNWM1V4dEFoQUdnOFhkdkVpT0YzLVF6Vk5vdEVhMzRkaC1FME1pa1hxeXotTUlUS1dsS3JoQmJDdUZGTzhSM09OMzJBU09OMkYtTzY3bUtOd21PODIzU0tRUXhwa0tXTjZha3pQX3NGX1hiMnlKREdqWFJzSGxOMDFWdVM2eDVVQVEzRnZweFVCY3dNY3ZmY1NFaWFFR0ZZYVBjM3FpSHB3Y1l1X29UX3dVRi1vb1NnVkVmRUpNQ3RYcFUtYURtdnZ2a0Z6QTdnWjRuVDlwLVIwa2V6cVhqbmZsVEMyMjZEMHFORXBTeU1ZckJrN1AtMUdOTi1Md0RiaG9zeUdzYUNZT1VWT3hKeG9wSnpoNlhOdmhGSkduMTBhanpNeFEycEhEMngyS200ZTVybm5MZGVsLWRxMnlLSTV1bU1SN19ERnVMUzFTcmhqVHdWZzZHazdMRTR0R3p6SmRIcC1xdjViMjhJOVZZNC05Zy10Z2tvTjI4aXZaN3ZWbXpIb0V1eHNmdEctMFhjTF9UT3dRQ1YtZThsTkZod1N5WGV0eWRBbk16cTdvYWxMdS10aURnbDlsVktPcTF3ZWtianEzZTdKR1RyNVVjMkFyVmhSWHRXSkhKSXJGOGliZEhMbmhyeHg3V25JU0xSYUJPbXpONTNDcXQ0TURPdWxNTnJhOUE2bW5oWTZyb0FHUUJmUTZQVWlBVVFlQUtmNlJXZ3VtaEY2Q0htMG5kRFdrQ1FoOUZNanlGc0gxejZPR0RfWEM2Z2pabWVjVWFQU1h3OENJdGhuaHNtWHVLcE1MRUloR21RMkJlaUktYWRKd3RWcXhzNTRVclVCemdNT0M0Y0JmaGZxaXFoeDlMOW9FZFlTYnE4YjJiZV9UWUpJY0RWRGxoMmZjZ3Y4NHRQU1ZyaVJqYUhKYUx3TUtzS1V6V200YTR5RURZOFhxR05GQVNtQWFXTWZrY1UzeW5sMmhqUExsdnpNYVI1T1M3UWNWTWkwalB0WW56VlQ3U2luWmxIelF4R1pockdUc3ZDSXlDazFsNnh6aExKRGtVN19uSUtlVHhZVGdtTDJPQzZScWZDbWpFRnJMRlR2RF8yUC0waFRkUURsbll5a3JpV29ZdmpmNm03MWRzOEhuRGVWTEtfc01qVldneHZ1UEhtRTJubzZaUVI5dkxhTkF4WDRUOG9Xejlud24yYXBqdktqdkkwVDN0LV9YclRMa19aQVpZNVZuVkVjenEzNHZWekVrdTlRUXk1anU3d2JhMVptdmo1SVRFVVQ2azB3YlJOUkdpYmxIQTNLbllyakVmbU9xTWEtSzBWY29tcktfbUVhNjBUbFhoVkhHaGRxemg1a2VLTEtLQ2daSW91ZVRra1FkaTBDQ2FWMUczdXNXb2VMZ1IwRTI1X1B5U1hnMk9fSGZYaHhFRkJkN1NFeXdFSVNNTDdETUR0T19wdExtb1hUaHpyVTJZemU1SnFreXdpd1Rjbk1nSFlUT21FdjZ6LVZGS29LMWVYMjNkNXNyVTFseWVmajZqdElvOU9faTNNQmFnQ1dSRHA5Wi1kOHFiUGdTdFg1VWJJcXpxNWNFM3BQQ2llWHRqenhVb3BOWC1lel9OMDB4OXpITFhmVEVUSDk5TzJRdzFldUQ1aTJWSEhQUkYyd1FQMm5RQnJwSjdKelV4ME5nZjhmc0pVNlp6OGlpLWgyZmkxb3loQnM1ZHVaUkdzMVlOZGh4TnhNTnhjajRvTmpiclV3c21KZmVxMUItZ2Y1d19BWDFCbVJETWxFNGtFbS1MbFd4OTlXNWlKTEViTVdrZUZiZkdqMHp0QWxoWlhGak9JTmF4ZzRZN3lacEU2RTN2ZHFXemVLazduLXpGV1BQN1JwS2R0ck1yZkQxMjhva3ZUbGRpOEVER2pJMm8yR1NYWVh5MG9XLVMydnQ1NXNraWI1WG82dEtDY2xocEV0T0Yt)
      xcode: latest
      node: latest
      npm: latest

    scripts:
      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: keychain initialize

      - name: Fetch signing files
        script: |
          # You can allow creating resources if existing are not found with `--create` flag
          app-store-connect fetch-signing-files "$(xcode-project detect-bundle-id)" \
            --type IOS_APP_DEVELOPMENT \
            --create      

      - name: Set up signing certificate
        script: keychain add-certificates

      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles

      - name: Install npm dependencies
        script: npm install

      - name: Install CocoaPods dependencies
        script: cd ios && pod install

      - name: Build ipa for distribution
        script: xcode-project build-ipa --workspace "$FCI_BUILD_DIR/ios/Wallet.xcworkspace" --scheme "Wallet"

    artifacts:
      - build/**/outputs/**/*.aab
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - codemagic@stayradiated.com
        notify:
          success: true
          failure: false

      app_store_connect:
        apple_id: apple@stayradiated.com
        password: Encrypted(Z0FBQUFBQmdzMHFpbkdvcGJuRWRYcFJHREdPdURRVzEyMmhrMUtDT1RQMFg1Y0UyR0VJQVpOV29aMEtXYWtVVnl3clhBNi1oY1dNQlBQQzVQSmF5amV3SnA4dXl6V3NEZmozeHR6ZkdZZW5HcF9RdkM0ODg5OFk9)

